##### indexing #####
set -g base-index 1
set -g pane-base-index 1

##### prefix #####
set-option -g prefix C-b
bind C-b send-prefix

##### pane management #####
unbind x
bind x kill-pane

unbind '"'
unbind %

bind-key -n C-t split-window -h -c "#{pane_current_path}"
bind-key -n C-y split-window -v -c "#{pane_current_path}"
bind-key -n C-u previous-window
bind-key -n C-i next-window
bind-key -n C-n new-window -c "#{pane_current_path}"
bind-key -n C-x kill-pane

##### pane focus (ctrl + key, no prefix) #####
bind-key -n C-k select-pane -U  # focus up
bind-key -n C-j select-pane -D  # focus down
bind-key -n C-h select-pane -L  # focus left
bind-key -n C-l select-pane -R  # focus right

##### pane resize (with prefix ctrl-b + key) #####
bind k resize-pane -U 2  # resize up
bind j resize-pane -D 2  # resize down
bind h resize-pane -L 2  # resize left
bind l resize-pane -R 2  # resize right

##### mouse and history #####
set -g mouse off
set -g history-limit 100000

##### colors and appearance #####
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins"

##### tmux plugins #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'

##### plugin settings #####
# tmux-resurrect settings
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-restore-bash-history 'on'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

# tmux-continuum settings
set -g @continuum-restore 'off'
set -g @continuum-save-interval '15'

# tmux-yank settings
set -g @yank_selection_mouse 'clipboard'

##### initialize tmux plugin manager #####
run -b '~/.config/tmux/plugins/tpm/tpm'
