#!/usr/bin/env python3
"""
Highlight Hyprland workspaces in Waybar when new windows appear on non-active workspaces.

The script polls Hyprland clients/workspaces once a second using `hyprctl -j` and notes
when a window spawns or moves to a different workspace that isn't currently focused.
Those workspace ids are written to `~/.config/waybar/style-workspace-flash.css` which
is @import-ed by Waybar's stylesheet. Each update triggers a lightweight Waybar reload
so the CSS changes take effect immediately.
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Set

CSS_PATH = Path.home() / ".config/waybar/style-workspace-flash.css"
CSS_HEADER = "/* Autogenerated by workspace_flash.py — do not edit manually. */\n"
POLL_SECONDS = 1.0
LOG_PATH = Path.home() / ".local/state/workspace_flash.log"


def log(message: str) -> None:
    try:
        LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        LOG_PATH.open("a", encoding="utf-8").write(
            f"{datetime.now().isoformat()} {message}\n"
        )
    except Exception:
        pass


def hyprctl_json(section: str) -> object:
    """Run `hyprctl -j <section>` and decode the JSON result."""
    result = subprocess.run(
        ["hyprctl", "-j", section],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        msg = result.stderr.strip() or f"hyprctl -j {section} failed"
        log(f"hyprctl error for {section}: {msg}")
        raise RuntimeError(msg)

    payload = result.stdout.strip()
    if not payload:
        return {}
    return json.loads(payload)


def workspace_order(workspaces: Iterable[dict]) -> Dict[int, int]:
    """
    Map workspace ids to the (1-based) visual order Waybar renders them in.
    Falls back to the workspace id if Hyprland doesn't report the workspace.
    """
    ordered: Dict[int, int] = {}
    sortable: List[dict] = [
        ws for ws in workspaces if isinstance(ws.get("id"), int) and ws["id"] > 0
    ]
    for idx, ws in enumerate(sorted(sortable, key=lambda item: item["id"]), start=1):
        ordered[ws["id"]] = idx
    return ordered


def render_css(pending: Set[int], order_map: Dict[int, int], blink_on: bool) -> str:
    """Generate CSS rules that blink by swapping styles on every poll."""
    if not pending:
        return CSS_HEADER + "/* No pending workspace alerts. */\n"

    if blink_on:
        bg = "rgba(255, 71, 87, 0.85)"
        color = "#ffffff"
        shadow = "0 0 12px rgba(255, 71, 87, 0.95)"
    else:
        bg = "rgba(255, 71, 87, 0.25)"
        color = "#ffffff"
        shadow = "0 0 4px rgba(255, 71, 87, 0.35)"

    rules: List[str] = [CSS_HEADER]
    for workspace_id in sorted(pending):
        nth = order_map.get(workspace_id, workspace_id if workspace_id > 0 else 1)
        rules.append(
            (
                f"#workspaces button:nth-child({nth}):not(.active) {{\n"
                f"    background-color: {bg};\n"
                f"    color: {color};\n"
                f"    box-shadow: {shadow};\n"
                "    border: 1px solid rgba(255, 71, 87, 0.95);\n"
                "}\n"
            )
        )

    return "\n\n".join(rules) + "\n"


def reload_waybar() -> None:
    """Reload Waybar so the regenerated CSS is picked up."""
    subprocess.run(["pkill", "-USR2", "waybar"], check=False)


def main() -> int:
    CSS_PATH.parent.mkdir(parents=True, exist_ok=True)

    known_clients: Dict[str, int] = {}
    pending_workspaces: Set[int] = set()
    last_css = ""
    blink_on = False

    while True:
        blink_on = not blink_on

        try:
            clients = hyprctl_json("clients")
            workspaces = hyprctl_json("workspaces")
            monitors = hyprctl_json("monitors")
        except Exception:
            time.sleep(POLL_SECONDS)
            continue

        if not isinstance(clients, list):
            clients = []
        if not isinstance(workspaces, list):
            workspaces = []
        visible_ids: Set[int] = set()
        if isinstance(monitors, list):
            for mon in monitors:
                active_ws = (
                    mon.get("activeWorkspace") if isinstance(mon, dict) else None
                )
                ws_id = active_ws.get("id") if isinstance(active_ws, dict) else None
                if isinstance(ws_id, int):
                    visible_ids.add(ws_id)

        current_clients: Dict[str, int] = {}
        occupied: Set[int] = set()

        for client in clients:
            addr = client.get("address")
            workspace_info = client.get("workspace") or {}
            wid = workspace_info.get("id")
            if not isinstance(addr, str) or not isinstance(wid, int):
                continue

            current_clients[addr] = wid
            occupied.add(wid)

            previous = known_clients.get(addr)
            if previous != wid and wid not in visible_ids:
                pending_workspaces.add(wid)
                log(f"Queued workspace {wid} (client {addr})")

        known_clients = current_clients

        # Drop cleared workspaces
        cleared = pending_workspaces.intersection(visible_ids)
        if cleared:
            for ws_id in list(cleared):
                pending_workspaces.discard(ws_id)
                log(f"Cleared workspace {ws_id} (now visible)")
        pending_workspaces.intersection_update(occupied)

        css_blob = render_css(pending_workspaces, workspace_order(workspaces), blink_on)
        if css_blob != last_css:
            CSS_PATH.write_text(css_blob, encoding="utf-8")
            reload_waybar()
            last_css = css_blob

        time.sleep(POLL_SECONDS)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        pass
